version: '2'
services:
    m3-app:
        image: m3
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://m3-mysql:3306/m3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://m3-elasticsearch:9200
        ports:
            - 8080:8080
    m3-mysql:
        extends:
            file: mysql.yml
            service: m3-mysql
    m3-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: m3-elasticsearch
